# Leitura de Dados no Pandas

- Pandas oferece suporte de leitura a vários formatos, mais detalhas na [documentação oficial](https://pandas.pydata.org/docs/user_guide/io.html).

![Exemplo de read](https://pandas.pydata.org/docs/_images/02_io_readwrite.svg)

In [ ]:
# importação da biblioteca Pandas
import pandas as pd

## pd.read_json

In [ ]:
json = open('aluguel.json')
print(json.read())

[{"Tipo":"Quitinete","Bairro":"Copacabana","Quartos":1,"Vagas":0,"Suites":0,"Area":40,"Valor":1700.0,"Condominio":500.0,"IPTU":60.0},
{"Tipo":"Casa","Bairro":"Jardim Bot\u00e2nico","Quartos":2,"Vagas":0,"Suites":1,"Area":100,"Valor":7000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Conjunto Comercial\/Sala","Bairro":"Barra da Tijuca","Quartos":0,"Vagas":4,"Suites":0,"Area":150,"Valor":5200.0,"Condominio":4020.0,"IPTU":1111.0},
{"Tipo":"Apartamento","Bairro":"Centro","Quartos":1,"Vagas":0,"Suites":0,"Area":15,"Valor":800.0,"Condominio":390.0,"IPTU":20.0},
{"Tipo":"Apartamento","Bairro":"Higien\u00f3polis","Quartos":1,"Vagas":0,"Suites":0,"Area":48,"Valor":800.0,"Condominio":230.0,"IPTU":null},
{"Tipo":"Apartamento","Bairro":"Vista Alegre","Quartos":3,"Vagas":1,"Suites":0,"Area":70,"Valor":1200.0,"Condominio":null,"IPTU":null},
{"Tipo":"Apartamento","Bairro":"Cachambi","Quartos":2,"Vagas":0,"Suites":0,"Area":50,"Valor":1300.0,"Condominio":301.0,"IPTU":17.0},
{"Tipo":"Casa de Condom\u00ednio","Bairro":"Barra da Tijuca","Quartos":5,"Vagas":4,"Suites":5,"Area":750,"Valor":22000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Casa de Condom\u00ednio","Bairro":"Ramos","Quartos":2,"Vagas":2,"Suites":0,"Area":65,"Valor":1000.0,"Condominio":null,"IPTU":null},
{"Tipo":"Conjunto Comercial\/Sala","Bairro":"Centro","Quartos":0,"Vagas":3,"Suites":0,"Area":695,"Valor":35000.0,"Condominio":19193.0,"IPTU":3030.0}]

In [ ]:
df_json = pd.read_json('aluguel.json')
df_json

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000,19193.0,3030.0

## pd.read_table

In [ ]:
txt = open('aluguel.txt')
print(txt.read())

Tipo	Bairro	Quartos	Vagas	Suites	Area	Valor	Condominio	IPTU
Quitinete	Copacabana	1	0	0	40	1700	500	60
Casa	Jardim Botânico	2	0	1	100	7000
Conjunto Comercial/Sala	Barra da Tijuca	0	4	0	150	5200	4020	1111
Apartamento	Centro	1	0	0	15	800	390	20
Apartamento	Higienópolis	1	0	0	48	800	230
Apartamento	Vista Alegre	3	1	0	70	1200
Apartamento	Cachambi	2	0	0	50	1300	301	17
Casa de Condomínio	Barra da Tijuca	5	4	5	750	22000
Casa de Condomínio	Ramos	2	2	0	65	1000
Conjunto Comercial/Sala	Centro	0	3	0	695	35000	19193	3030

In [ ]:
df_txt = pd.read_table('aluguel.txt')
df_txt

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000,19193.0,3030.0

## pd.read_excel

In [ ]:
df_xlsx = pd.read_excel('aluguel.xlsx')
df_xlsx

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000,19193.0,3030.0

## read_html

In [ ]:
df_html = pd.read_html('dados_html_1.html')
df_html[0]

  FAIXA ETÁRIA UNAFISCO SAÚDE SOFT II SOFT PARTICIPATIVO      UNIQUE
0      00 A 18               R$218,99           R$192,60    R$334,48
1      19 A 23               R$263,63           R$207,67    R$380,06
2      24 A 28               R$322,44           R$224,26    R$464,39
3      29 A 33               R$402,05           R$258,63    R$566,68
4      34 A 38               R$455,17           R$306,37    R$664,61
5      39 A 43               R$489,29           R$417,93    R$742,72
6      44 A 48               R$582,65           R$495,24    R$869,47
7      49 A 53               R$718,86           R$562,64  R$1.046,29
8      54 A 58               R$908,54           R$721,00  R$1.355,74
9   59 OU MAIS             R$1.244,50         R$1.151,62  R$2.003,53

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Ohio'

# Ler todas as tabelas HTML da página
tabelas = pd.read_html(url)
tabelas[0]

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Class 1Class 1 U.S. senators belong to the ele...,Class 1Class 1 U.S. senators belong to the ele...,Class 1Class 1 U.S. senators belong to the ele...,Class 1Class 1 U.S. senators belong to the ele...,Class 1Class 1 U.S. senators belong to the ele...,Class 1Class 1 U.S. senators belong to the ele...,C,Class 3Class 3 U.S. senators belong to the ele...,Class 3Class 3 U.S. senators belong to the ele...,Class 3Class 3 U.S. senators belong to the ele...,Class 3Class 3 U.S. senators belong to the ele...,Class 3Class 3 U.S. senators belong to the ele...,Class 3Class 3 U.S. senators belong to the ele...
1,#,Senator,Party,Dates in office,Electoral history,T,C,T,Electoral history,Dates in office,Party,Senator,#
2,1,John Smith,Democratic- Republican,"Apr 1, 1803 – Apr 25, 1808",Elected in 1803.[1]Resigned.,1,8th,1,Elected in 1803.[1]Retired.,"Apr 1, 1803 – Mar 3, 1807",Democratic- Republican,Thomas Worthington,1
3,1,John Smith,Democratic- Republican,"Apr 1, 1803 – Apr 25, 1808",Elected in 1803.[1]Resigned.,1,9th,1,Elected in 1803.[1]Retired.,"Apr 1, 1803 – Mar 3, 1807",Democratic- Republican,Thomas Worthington,1
4,1,John Smith,Democratic- Republican,"Apr 1, 1803 – Apr 25, 1808",Elected in 1803.[1]Resigned.,1,10th,2,Elected in 1807.[2]Resigned.,"Mar 4, 1807 – Mar 3, 1809",Democratic- Republican,Edward Tiffin,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,38,119th,38,Elected in 2022.,"Jan 3, 2023 – present",Republican,JD Vance,37
152,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,38,120th,38,Elected in 2022.,"Jan 3, 2023 – present",Republican,JD Vance,37
153,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,To be determined in the 2024 election.,38,121st,39,To be determined in the 2028 election.,To be determined in the 2028 election.,To be determined in the 2028 election.,To be determined in the 2028 election.,To be determined in the 2028 election.
154,#,Senator,Party,Years in office,Electoral history,T,C,T,Electoral history,Years in office,Party,Senator,#
155,Class 1,Class 1,Class 1,Class 1,Class 1,Class 1,C,Class 3,Class 3,Class 3,Class 3,Class 3,Class 3

## pd.read_csv

[Mais detalhes](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # usando arquivos armazenados no drive

Mounted at /content/drive

In [ ]:
base = pd.read_csv ('/content/drive/MyDrive/MOVER AULAS/BASES DE DADOS/aluguel.csv', sep=';')
base

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [ ]:
tips = pd.read_csv('https://raw.githubusercontent.com/Rogerio-mack/Visualizacao-de-Dados-em-Python/main/data/tips.csv')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]